export const TRIGGER_WAITER_MESSAGE = 'TRIGGER_WAITER_MESSAGE';
export const TRIGGER_WAITER_COURSES_ERROR = 'TRIGGER_WAITER_COURSES_ERROR';
export const TRIGGER_WAITER_STOCK_ERROR = 'TRIGGER_WAITER_STOCK_ERROR';
export const TRIGGER_WAITER_SNOBBY_ERROR = 'TRIGGER_WAITER_SNOBBY_ERROR';
export const REMOVE_WAITER_MESSAGE = 'REMOVE_WAITER_MESSAGE';
