export const CREATE_NEW_BOOKING = 'CREATE_NEW_BOOKING';
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const CREATE_NEW_SHARED_ORDER = 'CREATE_NEW_SHARED_ORDER';
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const ADD_TO_SHARED_ORDER = 'ADD_TO_SHARED_ORDER';
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER';
export const REMOVE_FROM_SHARED_ORDER = 'REMOVE_FROM_SHARED_ORDER';
export const RESET_ORDER = 'RESET_ORDER';
